# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/


variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  #MYSQL_DATABASE: $MYSQL_DB
  #MYSQL_ROOT_PASSWORD: $MYSQL_PASS

stages:
  - setup
  - sonarcloud
  - test

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - frontend/node_modules/
    - target/


setup:
  stage: setup
  image:
    name: mysql:latest
  allow_failure: false
  artifacts:
    when: always
    paths:
      - target/
      - frontend/coverage/lcov.info
    expire_in: 1 week
  script:
    #- if [ -z "$MYSQL_DATABASE" ]; then echo "Env variable not set MYSQL_DATABASE"; exit 1 ; fi
    #- if [ -z "$MYSQL_PASS" ]; then echo "Env variable not set MYSQL_PASS"; exit 1 ; fi
    - mysql -V
    - echo "Execute this script in all jobs that don't already have a before_script section."
    - apt -y update 
    - apt-get install -y build-essential
    - apt install -y curl
    - echo 'Installing nodejs & npm now'
    - curl -sL https://deb.nodesource.com/setup_14.x  | bash -
    - apt-get install -y nodejs
    - npm --version
    - node --version
    - echo 'Installing java'
    - mkdir -p /usr/share/man/man1
    - apt-get update -y && apt-get install -y default-jre
    - java -version
    - echo 'Compiling java classes'
    - sh mvnw compile
    - echo 'Folder structure after compile'
    - ls -a
    - echo 'Running tests & creating coverage report for frontend'
    - cd frontend
    - npm install
    #- npm i -g nyc
    #- npm run db && ./node_modules/.bin/nyc --reporter=html --reporter=text --require babel-core/register .node_modules/.bin/mocha --recursive ./server/test/integration/endpoints/ --exit
    - npm run build
    #- npm run coverage #JEST NOT SET UP YET
    


sonarcloud:
  stage: sonarcloud
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - echo 'Displaying current folder structure before start'
    - ls -a
    - sonar-scanner


# Security scans
include:
- template: Security/SAST.gitlab-ci.yml
sast:
    rules:
      - if: '$CI_COMMIT_BRANCH == "master"'
